import { Country, Indicator } from './types';

export const COUNTRIES: Record<string, string> = {
  // Africa
  'nigeria': 'NGA',
  'ghana': 'GHA',
  'kenya': 'KEN',
  'south africa': 'ZAF',
  'ethiopia': 'ETH',
  'tanzania': 'TZA',
  'uganda': 'UGA',
  'rwanda': 'RWA',
  'senegal': 'SEN',
  'ivory coast': 'CIV',
  "cote d'ivoire": 'CIV',
  'sierra leone': 'SLE',
  'cameroon': 'CMR',
  'egypt': 'EGY',
  'morocco': 'MAR',
  'mauritania': 'MRT',
  'mali': 'MLI',
  'niger': 'NER',
  'algeria': 'DZA',
  'tunisia': 'TUN',
  'libya': 'LBY',
  'sudan': 'SDN',
  'angola': 'AGO',
  'mozambique': 'MOZ',
  'zambia': 'ZMB',
  'zimbabwe': 'ZWE',
  'botswana': 'BWA',
  'namibia': 'NAM',
  'democratic republic of congo': 'COD',
  'drc': 'COD',
  'congo': 'COG',

  // MENA
  'saudi arabia': 'SAU',
  'uae': 'ARE',
  'united arab emirates': 'ARE',
  'qatar': 'QAT',
  'jordan': 'JOR',
  'turkey': 'TUR',
  'iran': 'IRN',
  'iraq': 'IRQ',
  'israel': 'ISR',
  'lebanon': 'LBN',
  'kuwait': 'KWT',
  'oman': 'OMN',
  'bahrain': 'BHR',
  'yemen': 'YEM',

  // Europe
  'germany': 'DEU',
  'france': 'FRA',
  'uk': 'GBR',
  'united kingdom': 'GBR',
  'britain': 'GBR',
  'italy': 'ITA',
  'spain': 'ESP',
  'netherlands': 'NLD',
  'poland': 'POL',
  'belgium': 'BEL',
  'sweden': 'SWE',
  'austria': 'AUT',
  'switzerland': 'CHE',
  'norway': 'NOR',
  'denmark': 'DNK',
  'finland': 'FIN',
  'ireland': 'IRL',
  'portugal': 'PRT',
  'greece': 'GRC',
  'czech republic': 'CZE',
  'czechia': 'CZE',
  'romania': 'ROU',
  'hungary': 'HUN',
  'ukraine': 'UKR',
  'russia': 'RUS',

  // Americas
  'usa': 'USA',
  'united states': 'USA',
  'us': 'USA',
  'america': 'USA',
  'canada': 'CAN',
  'mexico': 'MEX',
  'brazil': 'BRA',
  'argentina': 'ARG',
  'chile': 'CHL',
  'colombia': 'COL',
  'peru': 'PER',
  'venezuela': 'VEN',
  'ecuador': 'ECU',
  'bolivia': 'BOL',
  'paraguay': 'PRY',
  'uruguay': 'URY',
  'costa rica': 'CRI',
  'panama': 'PAN',
  'guatemala': 'GTM',
  'cuba': 'CUB',
  'dominican republic': 'DOM',
  'jamaica': 'JAM',

  // Asia
  'china': 'CHN',
  'japan': 'JPN',
  'india': 'IND',
  'indonesia': 'IDN',
  'malaysia': 'MYS',
  'thailand': 'THA',
  'vietnam': 'VNM',
  'pakistan': 'PAK',
  'bangladesh': 'BGD',
  'philippines': 'PHL',
  'south korea': 'KOR',
  'korea': 'KOR',
  'taiwan': 'TWN',
  'singapore': 'SGP',
  'hong kong': 'HKG',
  'myanmar': 'MMR',
  'burma': 'MMR',
  'cambodia': 'KHM',
  'laos': 'LAO',
  'nepal': 'NPL',
  'sri lanka': 'LKA',
  'afghanistan': 'AFG',

  // Oceania
  'australia': 'AUS',
  'new zealand': 'NZL',
};

export const REGIONAL_CODES: Record<string, string> = {
  'world': 'WLD',
  'global': 'WLD',
  'sub-saharan africa': 'SSF',
  'ssa': 'SSF',
  'africa': 'SSF',
  'middle east and north africa': 'MEA',
  'mena': 'MEA',
  'latin america': 'LCN',
  'latin america and caribbean': 'LCN',
  'lac': 'LCN',
  'europe and central asia': 'ECS',
  'europe': 'ECS',
  'east asia and pacific': 'EAS',
  'east asia': 'EAS',
  'south asia': 'SAS',
  'low income': 'LIC',
  'middle income': 'MIC',
  'high income': 'HIC',
  'oecd': 'OED',
  'euro area': 'EMU',
  'eurozone': 'EMU',
};

export const INDICATOR_SYNONYMS: Record<string, string> = {
  // GDP
  'gdp growth': 'NY.GDP.MKTP.KD.ZG',
  'economic growth': 'NY.GDP.MKTP.KD.ZG',
  'growth rate': 'NY.GDP.MKTP.KD.ZG',
  'growth': 'NY.GDP.MKTP.KD.ZG',
  'gdp': 'NY.GDP.MKTP.CD',
  'gross domestic product': 'NY.GDP.MKTP.CD',
  'gdp per capita': 'NY.GDP.PCAP.KD',
  'income per capita': 'NY.GDP.PCAP.KD',
  'gdp per person': 'NY.GDP.PCAP.KD',
  'real gdp': 'NY.GDP.MKTP.KD',
  'nominal gdp': 'NY.GDP.MKTP.CD',
  'structural transformation': 'NY.GDP.MKTP.KD.ZG',
  'economic transformation': 'NY.GDP.MKTP.KD.ZG',
  'economic development': 'NY.GDP.MKTP.KD.ZG',
  'economic performance': 'NY.GDP.MKTP.KD.ZG',
  'economy': 'NY.GDP.MKTP.KD.ZG',

  // Prices
  'inflation': 'FP.CPI.TOTL.ZG',
  'cpi': 'FP.CPI.TOTL.ZG',
  'consumer prices': 'FP.CPI.TOTL.ZG',
  'price level': 'FP.CPI.TOTL.ZG',
  'consumer price index': 'FP.CPI.TOTL.ZG',
  'prices': 'FP.CPI.TOTL.ZG',

  // Labor
  'unemployment': 'SL.UEM.TOTL.ZS',
  'jobless': 'SL.UEM.TOTL.ZS',
  'unemployment rate': 'SL.UEM.TOTL.ZS',
  'joblessness': 'SL.UEM.TOTL.ZS',
  'jobs': 'SL.UEM.TOTL.ZS',
  'employment': 'SL.UEM.TOTL.ZS',

  // External
  'current account': 'BN.CAB.XOKA.GD.ZS',
  'current account balance': 'BN.CAB.XOKA.GD.ZS',
  'trade balance': 'BN.CAB.XOKA.GD.ZS',
  'fdi': 'BX.KLT.DINV.WD.GD.ZS',
  'foreign investment': 'BX.KLT.DINV.WD.GD.ZS',
  'foreign direct investment': 'BX.KLT.DINV.WD.GD.ZS',
  'fdi inflows': 'BX.KLT.DINV.WD.GD.ZS',
  'exports': 'NE.EXP.GNFS.ZS',
  'export': 'NE.EXP.GNFS.ZS',
  'imports': 'NE.IMP.GNFS.ZS',
  'import': 'NE.IMP.GNFS.ZS',
  'trade': 'NE.TRD.GNFS.ZS',
  'trade openness': 'NE.TRD.GNFS.ZS',

  // Fiscal
  'debt': 'GC.DOD.TOTL.GD.ZS',
  'government debt': 'GC.DOD.TOTL.GD.ZS',
  'public debt': 'GC.DOD.TOTL.GD.ZS',
  'national debt': 'GC.DOD.TOTL.GD.ZS',

  // Social
  'population': 'SP.POP.TOTL',
  'poverty': 'SI.POV.DDAY',
  'poverty rate': 'SI.POV.DDAY',
  'extreme poverty': 'SI.POV.DDAY',
  'life expectancy': 'SP.DYN.LE00.IN',
  'life span': 'SP.DYN.LE00.IN',
  'inequality': 'SI.POV.GINI',
  'gini': 'SI.POV.GINI',
  'gini index': 'SI.POV.GINI',
  'gini coefficient': 'SI.POV.GINI',
};

// Multi-indicator queries - maps concept to multiple indicators
export const MULTI_INDICATOR_QUERIES: Record<string, string[]> = {
  'structural transformation': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic transformation': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'transformation story': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic overview': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic story': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'macroeconomic': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic snapshot': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic indicators': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic performance': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
  'economic development': ['NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.ZS'],
};

export const INDICATORS: Record<string, Indicator> = {
  'NY.GDP.MKTP.KD.ZG': { code: 'NY.GDP.MKTP.KD.ZG', name: 'GDP Growth', unit: '% annual' },
  'NY.GDP.MKTP.CD': { code: 'NY.GDP.MKTP.CD', name: 'GDP (current USD)', unit: 'USD' },
  'NY.GDP.MKTP.KD': { code: 'NY.GDP.MKTP.KD', name: 'GDP (constant 2015 USD)', unit: 'USD' },
  'NY.GDP.PCAP.KD': { code: 'NY.GDP.PCAP.KD', name: 'GDP per Capita', unit: 'USD constant 2015' },
  'FP.CPI.TOTL.ZG': { code: 'FP.CPI.TOTL.ZG', name: 'Inflation (CPI)', unit: '% annual' },
  'SL.UEM.TOTL.ZS': { code: 'SL.UEM.TOTL.ZS', name: 'Unemployment', unit: '% of labor force' },
  'BN.CAB.XOKA.GD.ZS': { code: 'BN.CAB.XOKA.GD.ZS', name: 'Current Account Balance', unit: '% of GDP' },
  'BX.KLT.DINV.WD.GD.ZS': { code: 'BX.KLT.DINV.WD.GD.ZS', name: 'FDI Inflows', unit: '% of GDP' },
  'GC.DOD.TOTL.GD.ZS': { code: 'GC.DOD.TOTL.GD.ZS', name: 'Government Debt', unit: '% of GDP' },
  'NE.EXP.GNFS.ZS': { code: 'NE.EXP.GNFS.ZS', name: 'Exports of Goods and Services', unit: '% of GDP' },
  'NE.IMP.GNFS.ZS': { code: 'NE.IMP.GNFS.ZS', name: 'Imports of Goods and Services', unit: '% of GDP' },
  'NE.TRD.GNFS.ZS': { code: 'NE.TRD.GNFS.ZS', name: 'Trade', unit: '% of GDP' },
  'SP.POP.TOTL': { code: 'SP.POP.TOTL', name: 'Population', unit: 'Total' },
  'SI.POV.DDAY': { code: 'SI.POV.DDAY', name: 'Poverty ($2.15/day)', unit: '% of population' },
  'SP.DYN.LE00.IN': { code: 'SP.DYN.LE00.IN', name: 'Life Expectancy', unit: 'Years' },
  'SI.POV.GINI': { code: 'SI.POV.GINI', name: 'Gini Index', unit: 'Index (0-100)' },
};

export const SUGGESTED_QUERIES = [
  "What's Nigeria's GDP growth over the last 10 years?",
  "Compare inflation in Egypt and Morocco since 2015",
  "Show me unemployment trends in South Africa",
  "FDI inflows to Kenya, Ethiopia, and Tanzania",
  "How has Sierra Leone's current account changed since 2010?",
  "Give me an economic snapshot of Mauritania",
];

export const CITATIONS: Record<string, string> = {
  worldbank: 'Source: World Bank Open Data. License: CC BY 4.0',
  oecd: 'Source: OECD Data. License: CC BY 4.0',
  fred: 'Source: Federal Reserve Economic Data (FRED), St. Louis Fed',
  eurostat: 'Source: Eurostat',
  fao: 'Source: FAOSTAT. License: CC BY 4.0',
  bis: 'Source: Bank for International Settlements',
  unctad: 'Source: UNCTADstat. License: CC BY 3.0 IGO',
};
